set_property SRC_FILE_INFO {cfile:C:/Users/prave/Desktop/FPGA_Snake_Game/Firmwares/Test_Buzzer/Test_Buzzer.srcs/constrs_1/new/constraints.xdc rfile:../../../Test_Buzzer.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports pwm_out]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
